[manager]
ratio          = [ 0, 5, 3 ]
sort_by        = "alphabetical"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

open = [ 
 { run = 'xdg-open "$1"',                desc = "Open", for = "linux" }, 
 { run = 'open "$@"',                    desc = "Open", for = "macos" }, 
 { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" }, 
] 
reveal = [ 
 { run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" }, 
 { run = 'open -R "$1"',                         desc = "Reveal", for = "macos" }, 
 { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" }, 
 { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" }, 
] 
