[manager]
ratio          = [ 0, 5, 3 ]
sort_by        = "alphabetical"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
